services:
  - type: web
    name: whatsapp-bot
    env: docker
    plan: free
    buildCommand: docker build -t whatsapp-bot .
    startCommand: docker run -p $PORT:3000 -e PORT=$PORT whatsapp-bot
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    numInstances: 1
    regions:
      - singapore
    disk:
      name: whatsapp-session
      mountPath: /app/.wwebjs_auth
      sizeGB: 1
