services:
  - type: web
    name: whatsapp-bot
    env: docker
    buildCommand: docker build -t whatsapp-bot .
    startCommand: docker run -p $PORT:3000 whatsapp-bot
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    branch: main
    numInstances: 1
    healthCheckTimeout: 100
